
language: objective-c
osx_image: xcode8.1
xcode_workspace: PushStarter.xcworkspace
xcode_scheme: PushStarter
xcode_sdk: iphonesimulator

before_install:
  - pod repo update

script:
  - xcodebuild clean build -workspace PushStarter.xcworkspace -scheme PushStarter -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1'

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master
    - swift3